version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4040:4040"  # Adjust if your app uses a different port
    restart: always

  cronjob:
    build:
      context: .
      dockerfile: Dockerfile.cron
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

